const { Router } = require("express");
const { progressRouter } = require("./leaderBoard");
const progressRouter = { Router };

//identifying the user on the basis of _id generated by mongoD
progressRouter.get("/:userId", async (req, res) => {
   try {
        const {userId} = req.params;
        const userProgress = await userModel.find({_id: userId});

        if(!userProgress){
            res.status(404).json({
                message: "User Not Found."
            })
    }   res.status(200).json(progress)
    } catch (error){
        res.status(500).json({
            message:"Server error", error
        });
    }
})

progressRouter.post("/dsa", requireAuth, async (req, res) => {
    try {const userId = req.userId;
    const date = Date.now();
    const type = 'DSA'
    const {hours, questions} = req.body;
    const progress = await progressModel.create({
        userId,
        date,
        type,
        hours,
        questions
    })

    res.status(201).json({
        message: "Progress Added", progress
    })
    } catch(error){
        res.status(500).json({
            message:"Something went wrong", error
        })
    }

    
});

progressRouter.post("/development", async (req, res) => {
    
});

progressRouter.post("/github", async (req, res) => {
    
});

progressRouter.post("/competitiveProgramming", async (req, res) => {
    
});


progressRouter.get("/dsa", async (req, res) => {

});

progressRouter.get("/development", async (req, res) => {
    
});

progressRouter.get("/github", async (req, res) => {
    
});

progressRouter.get("/competitiveProgramming", async (req, res) => {
    
});


module.exports = {
    progressRouter: progressRouter
}